name: my-first-workflow
# to get trigger on every push in the repo
on: 
  push: 
jobs:
  job1:
    name: JoB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step2-Checkout
        uses: actions/checkout@v6.0.2
      - name: step3
        run: |
          pwd
          ls -ltr
          hostname







  
    
