name: my-first-workflow
# to get trigger on every push in the repo
on: 
  push: 
jobs:
  job1:
    name: JoB1
    runs-on: ubuntu-latest
    steps:
      - name: Step-1
        run: |
          pwd
          ls -ltr
          hostname
      - name: step2-Checkout
        uses: actions/checkout@v6.0.2
      - name: step3
        run: |
          echo 'pwd' >> myartifact.txt
          mkdir artifact
          echo 'ls -ltr' >> artifact/list.txt
          echo 'hostname' >> artifact/host.txt
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: single_file
          path: ./myartifact.txt
      - name: upload2
        uses: actions/upload-artifact@v4
        with:
          name: directory
          path: artifact/
      - name: upload3
        uses: actions/upload-artifact@v4
        with:
          name: multiple
          path: |
            artifact/list.txt
            ./myartifact.txt
      - name: upload4
        uses: actions/upload-artifact@v4
        with:
          name: multiple_with_exclusion
          path: |
            ./myartifact.txt
            artifact/
            !**/hostname.txt              #exclusion
  job2:
    name: job2
    runs-on: ubuntu-22.04
    steps:
      - name: checking current directory
        run: |
          pwd
          ls -ltr
      - name: 
        uses: actions/download-artifact@v8
        wtih: 
          name: single_file
      - name: checking current directory post download
        run: |
          pwd
          ls -ltr






  
    
